DROP TABLE users CASCADE;
DROP TABLE dishes CASCADE;
DROP TABLE steps CASCADE;
DROP TABLE ingredients CASCADE;
DROP TABLE menus CASCADE;
DROP TABLE moderation CASCADE;
DROP TABLE ingredients_backup CASCADE;